### ISSUE TITLE
how to  generate gain_map.png

### ISSUE THREAD

**Issue by one2zero** [grapeot/AppleJPEGGainMap#1]
Can you explain how the gain_map.png in the project is generated?
I use other grayscale PNG images, and CGImageDestinationFinalize fails.

**Comment by grapeot** [comment]
It should be grayscale 8bit images. It's may worth double checking whether the used PNG file is RGB or Grayscale.

**Comment by grapeot** [comment]
I'm closing this issue for now since there is no further reply. But feel free to reopen it.
