### ISSUE TITLE
Fail to execute the scprit

### ISSUE THREAD

**Issue by bigipalabom** [grapeot/AppleJPEGGainMap#2]
Mac mini M2 Sonoma 14.1.1, xcode 15.0.1 installed

hi, I tried your code, with provided sample pictures in thie repository, but i got errors as below, any ideas?

swift main.swift

JIT session error: Symbols not found: [ _NSDeviceWhiteColorSpace, _OBJC_CLASS_$_NSBitmapImageRep ]
Failed to materialize symbols: { (main, { _symbolic SDySSypG, _$sSo27NSBitmapImageRepPropertyKeyas35_HasCustomAnyHashableRepresentationSCMc, _got.$ss5UInt8VMn, _symbolic Say_____G s5UInt8V, _$sSays5UInt8VGMD, _$sSo16NSColorSpaceNameaMB, _$sS2iSZsWl, _$sSSSgWOh, _$s6AppKitMXM, _got.$sSHMp, _$sSo16NSColorSpaceNameaMF, _$sypSgWOh, _$sSDySSypGWOh, _$s4main25writeAuxiliaryDataToImage05inputF4Path07gainMapH00I4Meta0I11Description06outputfH0ySS_SSSo18CGImageMetadataRefaSDySSypGSStF, _$sypWOb, _$sSSSgWOc, _$sSo16NSBitmapImageRepC16bitmapDataPlanes10pixelsWide0G4High13bitsPerSample07samplesK5Pixel8hasAlpha8isPlanar14colorSpaceName05bytesK3Row0jkN0ABSgSpySpys5UInt8VGSgGSg_S4iS2bSo07NSColortU0aS2itcfC, _$sSays5UInt8VGSayxGSlsWl, _got.$ss35_HasCustomAnyHashableRepresentationP03_tobcD0s0cD0VSgyFTq, _main, _$sSSWOh, _symbolic SS_ypt, _$sSays5UInt8VGWOh, _$sSo27NSBitmapImageRepPropertyKeyaABSHSCWL, _$sSo12NSDictionaryCML, _$sSo27NSBitmapImageRepPropertyKeyaMF, _symbolic yp_ypt, _$sS2iSZsWL, _$sSo27NSBitmapImageRepPropertyKeyaMB, _$syp_yptMD, _associated conformance So27NSBitmapImageRepPropertyKeyas20_SwiftNewtypeWrapperSCSY, _$sSo27NSBitmapImageRepPropertyKeyaML, _$ss5Error_pMD, _$sSo27NSBitmapImageRepPropertyKeyaMf, _got.$ss11AnyHashableVMn, _got.$sSYMp, _$sSoMXM, _$sSDySSypGMD, _$sSo27NSBitmapImageRepPropertyKeyaMn, _$sSS_yptMD, _got.$sSQMp, _$ss11AnyHashableV_yptMD, _got.$sSHSQTb, __swift_FORCE_LOAD_$_swiftQuartzCore_$_main, __swift_FORCE_LOAD_$_swiftMetal_$_main, _symbolic $sSY, _symbolic SS, _associated conformance So16NSColorSpaceNameas20_SwiftNewtypeWrapperSCSY, _$sSays5UInt8VGSayxGSlsWL, _got.$ss12_ArrayBufferVMn, _$sSo27NSBitmapImageRepPropertyKeya_yptMD, _symbolic ______ypt s11AnyHashableV, _$sSo27NSBitmapImageRepPropertyKeyaABs20_SwiftNewtypeWrapperSCWL, _$ss12_ArrayBufferVys5UInt8VGAByxGSTsWL, _$ss12_ArrayBufferVys5UInt8VGMD, _$sS2Ss21_ObjectiveCBridgeable10FoundationWL, _$sSays5UInt8VGSayxGSTsWl, _$sSo16NSColorSpaceNameaABSHSCWL, _$sSays5UInt8VGSayxGSTsWL, _$sSo16NSColorSpaceNameaSYSCSY8rawValue03RawE0QzvgTW, _$sSo27NSBitmapImageRepPropertyKeyaSHSCSH4hash4intoys6HasherVz_tFTW, __swift_FORCE_LOAD_$_swiftDarwin_$_main, _$sSo16NSColorSpaceNameaSYSCSY8rawValuexSg03RawE0Qz_tcfCTW, __swift_FORCE_LOAD_$_swiftCoreFoundation_$_main, _symbolic ______p s5ErrorP, _got.$sSY8rawValue03RawB0QzvgTq, _$s4main20imageDataFromCGImage7cgImage10Foundation0C0VSgSo0E3Refa_tF, _$sSo11CFStringRefaMf, _$s10Foundation4DataV5write2to7optionsyAA3URLV_So20NSDataWritingOptionsVtKFfA0_, _$sSo11CFStringRefaMn, __swift_FORCE_LOAD_$_swiftCoreGraphics_$_main, _$sSo27NSBitmapImageRepPropertyKeya8rawValueABSS_tcfC, _$sSo16NSColorSpaceNameaABSQSCWL, _$sSo11CFStringRefaML, _$sSo27NSBitmapImageRepPropertyKeyaSYSCMA, _$sSo27NSBitmapImageRepPropertyKeyaSHSCSH9hashValueSivgTW, _$sSo27NSBitmapImageRepPropertyKeyaSYSCSY8rawValue03RawG0QzvgTW, _$sSo27NSBitmapImageRepPropertyKeyaSYSCMc, _$sSo18CGImageMetadataRefaMn, _got.$sSY8rawValuexSg03RawB0Qz_tcfCTq, _got.$ss35_HasCustomAnyHashableRepresentationMp, _$sSo27NSBitmapImageRepPropertyKeyaSQSCSQ2eeoiySbx_xtFZTW, _$sS2is17FixedWidthIntegersWL, __swift_FORCE_LOAD_$_swiftOSLog_$_main, _$sSo16NSBitmapImageRepCML, __swift_FORCE_LOAD_$_swiftCoreImage_$_main, _$ss5Int32VABSzsWL, __swift_FORCE_LOAD_$_swiftos_$_main, __swift_FORCE_LOAD_$_swiftFoundation_$_main, __swift_FORCE_LOAD_$_swiftIOKit_$_main, __swift_FORCE_LOAD_$_swiftXPC_$_main, __swift_FORCE_LOAD_$_swiftDispatch_$_main, _got.$ss5ErrorMp, __swift_FORCE_LOAD_$_swiftObjectiveC_$_main, _got.$s15_ObjectiveCTypes01_A11CBridgeablePTl, _$sSo27NSBitmapImageRepPropertyKeyas21_ObjectiveCBridgeableSCMA, _$sSo27NSBitmapImageRepPropertyKeyaABSQSCWL, _symbolic _____ So27NSBitmapImageRepPropertyKeya, _symbolic $ss21_ObjectiveCBridgeableP, _$sSo27NSBitmapImageRepPropertyKeyas21_ObjectiveCBridgeableSCMc, _got.$ss21_ObjectiveCBridgeableMp, _$sSo27NSBitmapImageRepPropertyKeyaSHSCSH13_rawHashValue4seedS2i_tFTW, _got.$ss21_ObjectiveCBridgeableP09_bridgeToA1C01_A5CTypeQzyFTq, _$s4main15gainDescriptionSDySSypGSgvp, _symbolic _____ So16NSColorSpaceNamea, _$sSo16NSColorSpaceNameas21_ObjectiveCBridgeableSCMA, _$s4main18outputHDRImagePathSSvp, _$sSo16NSColorSpaceNameaSYSCMA, _$sSo16NSBitmapImageRepC16bitmapDataPlanes10pixelsWide0G4High13bitsPerSample07samplesK5Pixel8hasAlpha8isPlanar14colorSpaceName05bytesK3Row0jkN0ABSgSpySpys5UInt8VGSgGSg_S4iS2bSo07NSColortU0aS2itcfcTO, _$sSo16NSColorSpaceNameas21_ObjectiveCBridgeableSCMc, _$s4main8gainMetaSo18CGImageMetadataRefaSgvp, _$sSo27NSBitmapImageRepPropertyKeyaABSYSCWL, _$sSo18CGImageMetadataRefaMf, _$sSo27NSBitmapImageRepPropertyKeyaSQSCMc, _$sSo16NSColorSpaceNameaABs20_SwiftNewtypeWrapperSCWl, _got.$ss20_SwiftNewtypeWrapperMp, $.main.__inits.0, ___swift_instantiateConcreteTypeFromMangledNameAbstract, _got.$ss20_SwiftNewtypeWrapperPSYTb, _$sSDySSypGSDyxq_Gs21_ObjectiveCBridgeable10FoundationWl, _$sSo18CGImageMetadataRefaML, _$sSo27NSBitmapImageRepPropertyKeyaSHSCMc, _$sSo27NSBitmapImageRepPropertyKeya8rawValueSSvg, _$sSo16NSColorSpaceNameaABSYSCWL, _$sSo16NSColorSpaceNameaSHSCSH13_rawHashValue4seedS2i_tFTW, _got.$sSH4hash4intoys6HasherVz_tFTq, _got.$sSH13_rawHashValue4seedS2i_tFTq, _$sSo16NSColorSpaceNameaSHSCSH4hash4intoys6HasherVz_tFTW, _$sSo16NSColorSpaceNameaABSHSCWl, _$s4main12sdrImagePathSSvp, _$sSo27NSBitmapImageRepPropertyKeyaABSHSCWl, _$sSo18CGImageMetadataRefaMa, ___swift_instantiateConcreteTypeFromMangledName, _$sS2Ss21_ObjectiveCBridgeable10FoundationWl, _symbolic ______ypt So27NSBitmapImageRepPropertyKeya, _$ss5Int32VABSzsWl, _$sSo16NSColorSpaceNameaSQSCSQ2eeoiySbx_xtFZTW, _$sS2is17FixedWidthIntegersWl, _symbolic _____y_____G s12_ArrayBufferV s5UInt8V, _$sSo16NSBitmapImageRepCMa, _got.$sSH9hashValueSivgTq, _$sSo16NSColorSpaceNameaABs20_SwiftNewtypeWrapperSCWL, _$ss12_ArrayBufferVys5UInt8VGAByxGSTsWl, _associated conformance So16NSColorSpaceNameas20_SwiftNewtypeWrapperSCs35_HasCustomAnyHashableRepresentation, _$sSDySSypGSDyxq_Gs21_ObjectiveCBridgeable10FoundationWL, _$s12CoreGraphics7CGFloatVyACxcSzRzlufCSi_Tgq5, _$sSo12CGContextRefa12CoreGraphicsE4draw_2in8byTilingySo07CGImageB0a_So6CGRectVSbtFfA1_, _$s4main18referenceImagePathSSvp, __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_main, ___swift_project_boxed_opaque_existential_0, _$sSo27NSBitmapImageRepPropertyKeyas20_SwiftNewtypeWrapperSCMc, _$s10Foundation4DataV15_RepresentationOWOy, _got.$sSQ2eeoiySbx_xtFZTq, _$sSo27NSBitmapImageRepPropertyKeyas35_HasCustomAnyHashableRepresentationSCsACP03_toghI0s0hI0VSgyFTW, _associated conformance So16NSColorSpaceNameaSHSCSQ, _associated conformance So27NSBitmapImageRepPropertyKeyaSHSCSQ, ___swift_destroy_boxed_opaque_existential_0, _$ss26DefaultStringInterpolationVWOh, _symbolic So8NSStringC, _$sSo16NSColorSpaceNameas20_SwiftNewtypeWrapperSCMc, _$s4main16gainMapImagePathSSvp, _$s10Foundation4DataV15_RepresentationOWOe, _$sSo16NSColorSpaceNamea8rawValueABSS_tcfC, _$sSo16NSColorSpaceNameas21_ObjectiveCBridgeableSCsACP026_unconditionallyBridgeFromD1Cyx01_D5CTypeQzSgFZTW, _$sSo27NSBitmapImageRepPropertyKeyaABSYSCWl, _$sSo16NSColorSpaceNameaABSQSCWl, _$sSo16NSColorSpaceNamea8rawValueSSvg, _$sSo27NSBitmapImageRepPropertyKeyaABSQSCWl, _$sSo16CGImageAlphaInfoV8rawValues6UInt32Vvg, _$sSo16NSColorSpaceNameas21_ObjectiveCBridgeableSCsACP016_forceBridgeFromD1C_6resulty01_D5CTypeQz_xSgztFZTW, _$sSo16NSColorSpaceNameaABSYSCWl, _$sSo16NSColorSpaceNameaABs35_HasCustomAnyHashableRepresentationSCWL, _$sSo27NSBitmapImageRepPropertyKeyaMa, _$sSo16NSColorSpaceNameaSHSCSH9hashValueSivgTW, _$sSo11CFStringRefaMa, _$sSo12NSDictionaryCMa, _$sSa12_endMutationyyF, _$sSo27NSBitmapImageRepPropertyKeyaABs35_HasCustomAnyHashableRepresentationSCWL, _$s4main14extractGainMap13inputFilePath06outputfG0So18CGImageMetadataRefaSg_SDySSypGSgtSS_SSSgtF, _got.$ss21_ObjectiveCBridgeableP024_conditionallyBridgeFromA1C_6resultSb01_A5CTypeQz_xSgztFZTq, _$sSo27NSBitmapImageRepPropertyKeyas21_ObjectiveCBridgeableSCsACP026_unconditionallyBridgeFromF1Cyx01_F5CTypeQzSgFZTW, _got.$ss21_ObjectiveCBridgeableP016_forceBridgeFromA1C_6resulty01_A5CTypeQz_xSgztFZTq, _$sSo27NSBitmapImageRepPropertyKeyas21_ObjectiveCBridgeableSCsACP024_conditionallyBridgeFromF1C_6resultSb01_F5CTypeQz_xSgztFZTW, _$sSo16NSColorSpaceNameaABs35_HasCustomAnyHashableRepresentationSCWl, _$ss37_convertMutableArrayToPointerArgumentyyXlSg_q_tSayxGzs01_E0R_r0_lFSbyXEfu_SbyKXEfu0_, _$sSo27NSBitmapImageRepPropertyKeyas21_ObjectiveCBridgeableSCsACP016_forceBridgeFromF1C_6resulty01_F5CTypeQz_xSgztFZTW, _$ss37_convertMutableArrayToPointerArgumentyyXlSg_q_tSayxGzs01_E0R_r0_lFSbyXEfu_, _got.$ss21_ObjectiveCBridgeableP026_unconditionallyBridgeFromA1Cyx01_A5CTypeQzSgFZTq, _$sSo16NSColorSpaceNameas21_ObjectiveCBridgeableSCsACP024_conditionallyBridgeFromD1C_6resultSb01_D5CTypeQz_xSgztFZTW, _$ss27_finalizeUninitializedArrayySayxGABnlF, _$sSo27NSBitmapImageRepPropertyKeyaABs20_SwiftNewtypeWrapperSCWl, _$ss5print_9separator10terminatoryypd_S2StFfA0_, _$ss5print_9separator10terminatoryypd_S2StFfA1_, _$sSo27NSBitmapImageRepPropertyKeyaSYSCSY8rawValuexSg03RawG0Qz_tcfCTW, _$sSo27NSBitmapImageRepPropertyKeyaABs35_HasCustomAnyHashableRepresentationSCWl, _got.$ss20_SwiftNewtypeWrapperPs35_HasCustomAnyHashableRepresentationTb, _$sSo16NSColorSpaceNameaMf, _$sSo16NSColorSpaceNameas21_ObjectiveCBridgeableSCsACP09_bridgeToD1C01_D5CTypeQzyFTW, _$sSo16NSColorSpaceNameaSHSCMc, _$sSo16NSColorSpaceNameaML, _$sSo16NSColorSpaceNameas35_HasCustomAnyHashableRepresentationSCsACP03_toefG0s0fG0VSgyFTW, _$sSo16NSColorSpaceNameaSYSCMc, _$sSo16NSColorSpaceNameaMa, _$sSo16NSColorSpaceNameaSQSCMc, _$sSo27NSBitmapImageRepPropertyKeyas21_ObjectiveCBridgeableSCsACP09_bridgeToF1C01_F5CTypeQzyFTW, _$sSo16NSColorSpaceNameas35_HasCustomAnyHashableRepresentationSCMc, _$sSo16NSColorSpaceNameaMn, _associated conformance So27NSBitmapImageRepPropertyKeyas20_SwiftNewtypeWrapperSCs35_HasCustomAnyHashableRepresentation, _got.$s8RawValueSYTl }) }

**Comment by grapeot** [comment]
Interestingly I also got the same error as yours after migrating the code from my Macbook to Mac Mini. I solved it by creating a new XCode Mac Commandline project, and importing the `main.swift` in.

**Comment by grapeot** [comment]
Close due to lack of activity and a resolution provided. Feel free to reopen.
