### ISSUE TITLE
Issue about the format of the SDR.jpg

### ISSUE THREAD

**Issue by ProNoobLi** [grapeot/AppleJPEGGainMap#8]
Thanks for your great work and the code helps me a lot!

But I have an issue about the format of SDR JPG. Your white.jpg as input could generate the HDR effect, but my custom jpg/png
always returns the error like "addAuxiliaryDatalnfo:4453: *** ERROR: can't add depth/disparity to 'public.png'". Is your white.JPG
inserted any specific tags or additional data types?

Here is my screenshot png and may help you reproduce the error
![image](https://github.com/user-attachments/assets/a32b24aa-9fe4-4f84-a5b5-582bd1073136)

**Comment by ProNoobLi** [comment]
Done, 
You are right. The SDR image should be in the real JPG format, and modify the extension from png to jpg doesn't work

**Comment by grapeot** [comment]
Yes that should be the reason. Great you figured it out!
